#toml configurations
name = "App"
type = "python"
main = "main.py"
compatibility_date = "2023-11-05"


#database set up
[[d1_databases]]
binding = "DB"
database_name = "mapsapi-db"



# Command to install dependencies
[build]
command = "pip install -r requirements.txt"
