name = "mapsapi"
main = "main.py"
compatibility_date = "2023-11-05"

[[d1_databases]]
binding = "DB"
database_name = "mapsapi-db"

[build]
command = "pip install -r requirements.txt"

[site]
bucket = "./dist"  # Replace with your actual build output directory
entry-point = "workers-site"

[env.production]
pages_build_output_dir = "./dist"  # Replace with your actual build output directory
