"""created at friendship

Revision ID: e1f36d18da4a
Revises: b08864b87217
Create Date: 2024-10-31 19:36:30.911941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f36d18da4a'
down_revision: Union[str, None] = 'b08864b87217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendships', 'created_at')
    # ### end Alembic commands ###
